### ISSUE TITLE
4月16号 mini Backlog

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#213]
目前今日安排：
## # 今日重点调整！：
由**张翔** & **江同学** 负责
- [x] 1. 绑定 NEAR 后可以反复领取 VP
- [ ] 2. 每日投票次数和数量不限制
- [x] 3. 创建项目消费改为 10 VP

## 优化点-P1
- [x] - 删除个人主页Award Record--小田
- [x] - 修复个人主页Tags显示异常--小田
- [x] - 关注被关注redis--张翔
- [x] - 搜索、筛选、排序项目--小音
- [x] - 星标项目 功能+文字 调整--小音
- [x] 去掉首页疑惑的 `/article` -- Frank (#217)
- [x] - 提醒小红点显示逻辑优化--Frank
  - [x] 研究中
  - [x] 找到解决方案 (#219 by Frank)
- [x] - 稳定服务,提升体验--Frank、张翔
  - [x] 把图片压缩，每次请求省了1M的带宽，对非关键脚本进行了 defer (#224 #226 by Frank)
  - [x] `testing` 前端，针对中国的访问优化，改走新加坡中国电信CN2线路（by Frank）
![](https://user-images.githubusercontent.com/3261732/79422359-5351c300-7fef-11ea-9b92-57c0c63e6176.png)
- [x] 扩展NAME长度限制（100字符）
- [x] 首次创建项目的时候五图无法被保存下来
- [x] 项目的动态设置和直播设置没有了

## 修改身份选项
- Engineer
- Designer/Illustrator
- Growth HAcker
- Performance MAketer
- Blogger/Writer/Journalist
- Product MAnager/Product Owner
- Crypto Economist/Economist
- Philosopher
- Artist
- Game Designer
- Investor/Philanthropist
- Other
-

**Comment by xiaotiandada** [comment]
> 大家自行补充

**小田**
 1. Update Setting  Page Word ....
 2. 手动清理一些脏数据
3. remove Award Records module, update word (user page)
4. 删除user下面的几个废弃页面
