### ISSUE TITLE
增加“KYC认证” 检测

### ISSUE THREAD

**Issue by guanchao71** [DAOJAM/DAO_Jam#34]
在DAOJAM中，为防止有用户大量刷票或是恶意使用，要求每位用户进行基础的KYC认证。

- [x] ~~认证的方式就是绑定邮箱账号+Github账号~~ 改为 Near 登录网站验证，当绑定完成后，用户自动获得100投票券奖励 (相关 issue #42)
- [x] 当新用户登录后，主动弹窗提示用户前去绑定账号
  - [x] 后端需要一个判断用户绑定与否的接口，用于前端 #68 by Frank [👉接口详情👈](https://github.com/DAOJAM/DAO_Jam/issues/68#issuecomment-606446702)
  - [x] 前端需要检测用户绑定账号状态，没绑定则提醒 by Frank
    <img width="426" alt="image" src="https://user-images.githubusercontent.com/3261732/78108534-2cf62a00-742a-11ea-99e2-2518bf7a4ac7.png">
   前端的 API 
```js
      const { data } = await this.$API.getKycStatus()
      if (!data.verified) { // 未绑定邮箱和 GitHub 的处理方法 }
      else { // 已绑定邮箱和 GitHub 的处理方法 }
```
- [x] 当用户点击领取新人奖励时，检测绑定账号状态，如果无绑定则提醒 #77 by Frank
   <img width="728" alt="image" src="https://user-images.githubusercontent.com/3261732/78110451-91ff4f00-742d-11ea-8421-4616e76ddb4d.png">
（仅实现了判断，未实现领取奖励的逻辑）
- [x] 当用户点击创建项目时，在支付环节，检测绑定账号状态，如果无绑定则提示用户前去绑定账号#16
- [x] 当用户在项目详情页点击投票时，检测并调试用户前去绑定账号

在用户没有绑定邮箱和Github账号的时候，实际上是无法通过正常渠道获得投票券奖励的

![image](https://user-images.githubusercontent.com/10827774/77269199-21e12280-6ce3-11ea-8cb7-81be4d27a319.png)
